FROM composer:latest

WORKDIR /var/www/html

# ENTRYPOINT [ "composer", "--ignore-platform-reqs" ]
ENTRYPOINT [ "composer" ]

# docker compose run composer install --ignore-platform-reqs

# или вот так на разных версиях Docker
# docker-compose run composer install --ignore-platform-reqs