version: "3.8"

services:
  web:
    build:
      context: apache
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - APACHE_RUN_USER=#1000
      - COMPOSER_MEMORY_LIMIT=-1
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=root
      - DB_PASSWORD=root
    volumes:
      - ../:/var/www/html
    ports:
      - 3000:80

  db:
    image: mariadb:10.3 # mariadb:10.2.44
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root             # пароль для базы данных (логин по умолчанию root)
      MYSQL_DATABASE: laravel        # имя базы данных

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db:db
    ports:
      - 9095:80                             # 9095 - порт по к-рому доступен phpMyAdmin вне контейнера (т.е. http://localhost:9095 )
    environment:
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - db

  composer:
    build:
      context: composer
      dockerfile: Dockerfile
    volumes:
      - ../:/var/www/html

#  docker compose up
#  docker compose up -d   // запуск в фоновом режиме
#  docker compose donwn