version: "3.8"

services:
  web:
    build:
      context: apache
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ../:/var/www/html
    ports:
      - 3000:80

#  docker compose up
#  docker compose up -d   // запуск в фоновом режиме
#  docker compose donwn

# или вот так на разных версиях Docker
#  docker-compose up
#  docker-compose up -d   // запуск в фоновом режиме
#  docker-compose donwn